hacklab-fi/asylum

- project/access/admin.py
- project/access/migrations/0001_initial.py
- project/access/models.py
- project/access/tests.py
- project/access/views.py
- project/config/settings/common.py
For flexible token and ACL management
> access control app

- Dockerfile
Optimise build speed when changing project files and not requirements (10s of seconds to less than 10)
> Optimise build speed 

- project/config/settings/common.py
- project/creditor/admin.py
- project/creditor/migrations/0001_initial.py
- project/creditor/models.py
- project/creditor/tests.py
- project/creditor/views.py
- project/members/models.py
> App for tracking member "credit" account

- project/README.md
- project/creditor/admin.py
- project/creditor/management/commands/addrecurring.py
- project/creditor/migrations/0002_auto_20151128_1321.py
- project/creditor/models.py
And helper methods to create transactions from the recurrence rules
> New model for recurring transactions (refs #13)

- project/.gitignore
- project/README.md
- project/asylum/static_src/less/asylum/variables.less
- project/asylum/static_src/less/style.less
- project/asylum/templates/base.html
- project/config/urls.py
- project/members/templates/members/application_form.html
- project/members/templates/members/application_received.html
- project/members/urls.py
- project/members/views.py
> BS3 base template

- project/config/settings/common.py
- project/members/forms.py
- project/members/views.py
Also added a new config key for the rules URL that can be simply set via .env
> Require applicant to accept rules, fixes #29

- project/creditor/migrations/0003_auto_20151128_1923.py
- project/creditor/migrations/0004_auto_20151128_1933.py
- project/creditor/migrations/0005_auto_20151128_1949.py
- project/creditor/models.py
This is a 64 char string, meant to be a hex representation of a hash or UUID
> Add unique id to transaction model fixes #37

- project/members/importer.py
- project/members/management/commands/importmembers.py
And a management command to pass a file to it.
CSVFile first row headers must match Member model
properties to be imported
> Simple CSV members importer, fixes #50

- project/access/models.py
- project/asylum/models.py
- project/creditor/models.py
- project/members/models.py
- project/ndaparser/models.py
> Add AsylumModel baseclass and use it everywhere, fixes #67

- project/creditor/locale/fi/LC_MESSAGES/django.po
- project/creditor/migrations/0006_auto_20151205_1933.py
- project/creditor/models.py
And check that we are within (time)scope before adding transaction.
Fixes #79
> Add start and end fields to RecurringTransaction

- project/asylum/util.py
- project/config/settings/common.py
- project/creditor/handlers.py
- project/creditor/migrations/0007_transactiontag_tmatch.py
- project/creditor/models.py
- project/env.example
- project/examples/handlers.py
- project/members/handlers.py
- project/ndaparser/admin.py
- project/ndaparser/templates/ndaparser/admin/upload.html
- project/ndaparser/views.py
- Fixes #61 
- Fixes #60
- Refs #36
- Depends on #92 (and whatever that depends on)
> Implement transaction importing callback system and example using it

- docker/run_unit_tests.sh
- project/run_tests.sh
TODO: test runner that doesn't use test databases since testing is done on docker image.
> Scripts to run unit tests

- docker/test_pull_request.sh
- Make sure upstream remote is defined
- Use githubs pull/ID special branch for pull-request
- auto-rebase to master
- auto-stop if commands fail
> Make this test script better

- project/access/management/commands/exporttokens.py
- project/access/migrations/0004_auto_20151211_0546.py
- project/access/models.py
- project/access/utils.py
- project/members/models.py
It's not quite https://github.com/rambo/nfc_lock/blob/master/python/keyserver.py compatible, but this format is better, I'll update keyserver.py Real Soon Now(tm)
> Add command to export sqlite file of token values and acls, fixes #59

- project/creditor/management/commands/addrecurring.py
- project/creditor/models.py
Also show the transactions created with the addrecurring command
Fixes #119
> Fix a problem in timescope checking for recurring transactions

- project/creditor/handlers.py
- project/creditor/migrations/0008_auto_20151226_2116.py
- project/creditor/models.py
- project/examples/handlers.py
- project/ndaparser/views.py
> Make it possible to set the transaction timestamp

- project/access/admin.py
- project/access/models.py
Depends on #120,  #122 and #102 (has also one migration)
> Access admin fixes

- project/creditor/admin.py
- project/creditor/models.py
Depends on #120,  #122 and #102 (has also one migration)
> Creditor admin fixes

- project/asylum/apptemplateloader.py
- project/asylum/static_src/js/asylum.js
- project/asylum/templates/admin/change_form.html
- project/config/settings/common.py
- project/config/settings/production.py
- project/gulpfile.js
And load it in admin too.
Fixes #105 
Not that I could trigger the problem before either, probably my VM just responds too fast.
> Add jQuery hook to prevent form double submissions

- project/access/locale/fi/LC_MESSAGES/django.po
- project/asylum/static_src/less/style.less
- project/config/settings/common.py
- project/creditor/locale/fi/LC_MESSAGES/django.po
- project/members/forms.py
- project/members/locale/fi/LC_MESSAGES/django.po
- project/members/templates/members/application_form.html
- project/ndaparser/locale/fi/LC_MESSAGES/django.po
Fixes #105 
Remember to rebuild your CSS with gulp if not rebuilding the whole Docker image.
> Signup form improvements/fixes

- Dockerfile
> Add apt-get update before installs

- README.md
- project/config/settings/common.py
- project/config/urls.py
Also document how to obtain tokens and query data.
Fixes #156
> Add token based authentication to REST API

- project/members/models.py
> Set notes regardless of whether membertypes are added

- Dockerfile
> Create known REST auth token for admin

- project/env.example
> #173 Fixed name of ADMIN_URL to correct variable

- README.md
- project/manage.py
Update production setup instructions
Based on a test install to a fresh 14.04 LTS
> Update production setup instructions

- project/access/management/commands/exporttokens.py
- project/access/utils.py
Fixes #169
Fixes #140 
Depends on #170
> Export token type as well and export external ids as json

- project/config/settings/production.py
- project/config/wsgi.py
- project/env.example
In case there isn't one availbale
Fixes #172
> Make sentry use configurable

- project/members/admin.py
> Restore the approval form, it was supposed to be removed in another branch

- project/members/admin.py
- project/members/locale/fi/LC_MESSAGES/django.po
> Member city and filter in admin view

- project/asylum/utils.py
- project/creditor/management/commands/addrecurring.py
- project/holviapp/management/commands/import_holvidata.py
> Implement "since" to addrecurring management command

- Dockerfile
- README.md
- docker/dev.sh
- docker/run_unit_tests.sh
- docker/start.sh
- docker/test_pull_request.sh
- project/creditor/tests/fixtures/recurring.py
- project/requirements.apt
- project/requirements/base.txt
- project/requirements/local.txt
- project/requirements/production.txt
- project/requirements/test.txt
- project/setup.cfg
Supercedes #190 (see that for details though).
Also updates the Dockerfile and apt requirements for Ubuntu 16.04 which fixes #196
> PyUp updates rebased and fixed

- .dockerignore
- .gitignore
- docker/dev.sh
- docker/run_unit_tests.sh
- docker/start.sh
- docker/test_pull_request.sh
- project/run_tests.sh
> Check for docker permissions first, also better check for existing image

- project/members/tests/test_application.py
- project/members/tests/test_restapi.py
> Add some tests for the web UIs for memberships

- .dockerignore
- project/run_tests.sh
Just in case there were missing migrations
Also ignore some node/bower stuff in the Docker context.
> Migrate before tests

- project/creditor/locale/fi/LC_MESSAGES/django.po
- project/creditor/migrations/0010_auto_20190131_1731.py
- project/creditor/models.py
- project/creditor/tests/fixtures/recurring.py
- project/creditor/tests/test_recurring.py
See https://github.com/hacklab-fi/asylum/pull/272 for more info.
> Fix bugs in https://github.com/hacklab-fi/asylum/pull/272

- project/access/rest.py
- project/creditor/rest.py
- project/members/rest.py
> Explicit all fields allow is now required

- project/members/admin.py
- project/members/forms.py
in 99.99% of cases it's an user error.
If you really need to make one create it via creditor admin or API
> Do not allow positive amount recurringtransactions in member admin
